language: java
jdk:
- oraclejdk8
before_install:
- chmod +x gradlew
- export JAVA_OPTS="-Xmx2048m -XX:MaxPermSize=386m"
install: ./gradlew assemble -Pskip.signing
before_deploy:
- export JARBALL=$(ls build/libs/elasticsearch-hadoop-5.5.0.jar)
deploy:
- provider: releases
  overwrite: true
  draft: false
  api_key:
    secure: gt5zjmIv4vKR7EptNGN7hLbdSaIxSlq1Zf94+y4gHw0/2izIFpkbOS/bGkkd6R3IqupgvqO6aXIdxRIMRhw79cqWpH2AxERk8ztqCqEM2CuuBybEGA5wjTsZYUFw8nqYeRa8qQESA+zimA9Hjc1h++rv2o8N/N+nq24i6vHEKCs7Htv4Lw2JL2v2NAPb/WGC2orqGdYqbZ5UnSPkPPMUtiaFoClAebD+YGTgVzHQL3PSUFAjwP1OoM1nURlFCmCsRoGoB/dwut7GQvHZlkzoVL1FzFKne3+1bFj90zO65SDOJsP3I39o1Weq0xvBFxs7FJw7pY4esi1gOerRV6xNl6JFeMr93LuF4x3tBihB3j0TdzLBs+2AdZF/jZxZhALAlYlBrbkrUybxjEuIX8RWq1jdAS5LsgK061ye8p0oN4/IRQY06U6FGo7gXPBuYThcTenNhs+Mwrm9/li3BpFcwCjPqqIYcUrAwsQzB/S2fEQ5qUlBEyR3MEIsxbEITzBKttYEJC9YX2wc4qsWXQZUbF3IusaVnts0quQDNo7VSiJsvM7BhRgJlYYWrrWc9GRAG9mRKSFfvNnek8x9YH9P4hMhKhsurxIwIlLeqd4M4HgKQa1K3YUemUMepsCdLPWclPN4Wq5xvrrLuMS/Zqg25gjmc/U9M5me+iej2cKUXHE=
  file:
  - $JARBALL
  skip_cleanup: true
  on:
    tags: true
    repo: strapdata/elasticsearch-hadoop
